### ISSUE TITLE
نصب

### ISSUE THREAD

**Issue by aminmardani** [abmahmoodi/redmine-persian#1]
سلام من یک نسخه مشابه یعنی دقیقا 3.3.1 را از سایت بیتنامی دانلود کردم و نصب کردن بعد فایل های شمارو جایگزین اون کردم و دستور 
bundle install --without development test 
رو هم اجرا کردم ولی اکثر صفحات خطا می دهد ضمن اینکه تقویم هم شمسی نمی شود
لطفا راهنمایی کنید جهت نصب ساده

**Comment by abmahmoodi** [comment]
همین پروژه را کلون بگیرید و سپس از طریق آدرس زیر مراحل نصب را طی کنید
https://redmine.org/projects/redmine/wiki/RedmineInstall

**Comment by aminmardani** [comment]
ممنون عالیه. کارتون حرف نداره
